import "../styles/globals.scss";
import "bootstrap/dist/css/bootstrap.min.css";
import { StoreProvider } from "../context/StoreContext";
import Navigation from "../components/Navigation";
import Head from "next/head";
import Footer from "../components/Footer";
import Footerbottom from "../components/Footerbottom";

function MyApp({ Component, pageProps }) {
  return (
    <StoreProvider>
      <Head>
        <title>Supermarket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <Component {...pageProps} />
      <Footer/>
      <Footerbottom/>
    </StoreProvider>
  );
}

export default MyApp;
