import Head from "next/head";
import Advertisement from "../components/Advertisement";
import Carousel1 from "../components/Carousel1";
import Carousel2 from "../components/Carousel2";
import Footer from "../components/Footer";
import Footerbottom from "../components/Footerbottom";
import Navigation from "../components/Navigation";
import Topselling from "../components/Topselling";


export default function Home() {
  return (
    <div >
      <Head>
        <title>Supermarket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />
      <Carousel1/>
      <Topselling/>
      <Carousel2/>
      <Advertisement/>
      <Footer/>
      <Footerbottom/>

    </div>
  );
}
